### ISSUE TITLE
Outdated source

### ISSUE THREAD

**Issue by caden1249** [br4nch/kayo#1]
Keep leaking outdated sources, we all know this is used on scare 😂 

https://on.soundcloud.com/krbnh4ys5tE7wAGk9

**Comment by caden1249** [comment]
also, you didn't leak this I did morons

**Comment by br4nch** [comment]
stop yapping caden

**Comment by alluding** [comment]
you cant code sadly caden & you're piss poor keep yappin poor loser

**Comment by alluding** [comment]
please down scare man, i know you have discord tokens that can down it https://scare.life/invite ill wait
